server:
  port: 8081

apache:
  spark:
    master: local[*]
    appname: twitter-mine

management:
  security:
    enabled: false

endpoints:
  sensitive: false
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
