
server:
  port: 8080

spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300,localhost:9301
      cluster-name: twitter-mine

apache:
  spark:
    master: local[*]
    appname: twitter-mine

endpoints:
  sensitive: false
  enabled: false
  info:
    enabled: true
  health:
    enabled: true

management:
  security:
    enabled: false
